FROM python:3.12.9

WORKDIR /app

COPY main.py intent_recognition.py openai_acess.py reranking.py retrieval.py ./
COPY utils/ ./utils/

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 8080

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8080"]
